# Environment
ENV_NAME = "Pendulum-v1"
NUM_ENVS = 2
INPUT_SIZE = 32
IMAGE_SIZE = 38
NO_OP_MAX_STEPS = 0
ACTION_REPETITIONS = 2
FRAMES_STACKED = 3
NUM_EPISODES = int(1e6)

# Logging
LOG_DIR = "logs"
EPISODES_PATIENCE = 128
EVAL_FREQUENCY = 10000
EVAL_EPISODE_COUNT = 5

# Training hyperparams
N_STEP_RETURNS = 3
MIN_START_STEPS = 1024
TARGET_UPDATE = 1
TAU = 0.005
INIT_ENTROPY_COEFF = 0.2
OPTIMIZATION_UPDATE = 2
NUM_GRADIENT_STEPS = 2
BATCH_SIZE = 256
CLIP_GRAD = 1
POLICY_LEARNING_RATE = 0.0001
ENTROPY_LEARNING_RATE = 0.0001
Q_VALUE_LEARNING_RATE = 0.0001
ENCODER_LEARNING_RATE = 0.0001
GAMMA = 0.99
NORMALIZE_VALUES = False
USE_CURL = True

# Network architecture
NUM_FC_HIDDEN_UNITS = 256
NUM_LATENT_DIMS = 128
NUM_CHANNELS = 64

# Replay buffer
REPLAY_BUFFER_LEN = int(1e5)
ALPHA = 0.75
BETA0 = 0.4
REPLAY_DELAY = 300
