# Environment
ENV_NAME = "Pendulum-v1"
INPUT_SIZE = 84
NO_OP_MAX_STEPS = 0
ACTION_REPETITIONS = 1
FRAMES_STACKED = 4
NUM_EPISODES = int(1e6)

# Logging
LOG_DIR = "logs"
EPISODES_PATIENCE = 128

# Training hyperparams
N_STEP_RETURNS = 1
MIN_START_STEPS = 2048
TARGET_UPDATE = 1
TAU = 0.005
ENTROPY_COEFF = 0.1
NUM_GRADIENT_STEPS = 1
BATCH_SIZE = 256
CLIP_GRAD = 1
POLICY_LEARNING_RATE = 0.0001
Q_VALUE_LEARNING_RATE = 0.0001
GAMMA = 0.99
NORMALIZE_VALUES = False

# Network architecture
NUM_FC_HIDDEN_UNITS = 128
NUM_CHANNELS = 64

# Replay buffer
REPLAY_BUFFER_LEN = int(1e5)
