# Environment
ENV_NAME = "Pendulum-v1"
NO_OP_MAX_STEPS = 0
ACTION_REPETITIONS = 1
FRAMES_STACKED = 4
NUM_EPISODES = int(1e6)

# Logging
LOG_DIR = "logs"
EPISODES_PATIENCE = 128

# Training hyperparams
N_STEP_RETURNS = 1
MIN_START_STEPS = 1024
TARGET_UPDATE = 1
TAU = 0.005
ENTROPY_COEFF = 0.1
NUM_GRADIENT_STEPS = 1
BATCH_SIZE = 64
CLIP_GRAD = 1
POLICY_LEARNING_RATE = 0.001
Q_VALUE_LEARNING_RATE = 0.001
GAMMA = 0.7
NORMALIZE_VALUES = False

# Network architecture
INPUT_SIZE = 84
NUM_FC_HIDDEN_UNITS = 128

# Replay buffer
REPLAY_BUFFER_LEN = int(1e5)
